# Generated by Django 5.2.17 on 2026-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="title or description"
                    ),
                ),
                ("responsible_person", models.CharField(max_length=100)),
                ("deadline", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
